### ISSUE TITLE
MoodReport POST API hook does not update Mood (Q1) and Stress Levels (Q2)

### ISSUE THREAD

**Issue by CANIS-NAU** [CANIS-NAU/ARORA-Server#17]
In MoodReport/views.py, the function does not actually update Q1 and Q2 with values from the POST request. It also does not update the corresponding user with respect to the last updated MoodReport timestamp.

**Comment by ashlemia** [comment]
**Why are Q1 and Q2 not being updated?**
The fields on a Mood Report POST or UPDATE call sent into the server must include "q1_response" and "q2_response", or else it is only taking the default assignment of 1 for both fields. 

The Postman Collection on the README has the wrong expected fields for Mood Reports CREATE and Mood Reports UPDATE. Both should be at least including "q1_response" and "q2_response" fields.

Within the app code, there is an attempt to be passing q1 and q2 fields.
![image](https://user-images.githubusercontent.com/82060474/170139239-3ae58c3e-7aa2-4191-a225-d56c7414adbb.png)

Doing a Postman Mood Report POST call with the fields "user_id", "q1_response", and "q2_response" does render "q1_response" and "q2_response" in the database appropriately, so this may not be a ARORA-Server issue.

**Why is the corresponding user not being updated?**
The mood report has the identifying "user_id" field, but never calls for an update on a user.
UserInfo needs to be updated with the created mood reports data (mood_report_created_at), either through a UserInfo UPDATE PUT call somewhere or manually getting and serializing UserInfo in the MoodReport POST and UPDATE section.
